name: Supabase Migrations Deploy

on:
  push:
    branches:
      - main
      - master
      - dev
    paths:
      - 'supabase/migrations/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: List Migrations
        run: ls -R supabase/migrations/

      - name: Deploy to DEV
        if: github.ref == 'refs/heads/dev'
        run: |
          supabase db push --db-url "${{ secrets.SUPABASE_DB_URL_DEV }}"
        
      - name: Deploy to PROD
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          supabase db push --db-url "${{ secrets.SUPABASE_DB_URL_PROD }}"
