name: Supabase Migrations Deploy

on:
  push:
    branches:
      - main
      - master
      - dev
    paths:
      - 'supabase/migrations/**'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy to DEV
        if: github.ref == 'refs/heads/dev'
        env:
          DB_URL: ${{ secrets.SUPABASE_DB_URL_DEV }}
        run: |
          if [ -z "$DB_URL" ]; then
            echo "::error title=Secret Missing::A secret SUPABASE_DB_URL_DEV não foi encontrada nas configurações do seu repositório GitHub."
            exit 1
          fi
          supabase db push --db-url "$DB_URL"
        
      - name: Deploy to PROD
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        env:
          DB_URL: ${{ secrets.SUPABASE_DB_URL_PROD }}
        run: |
          if [ -z "$DB_URL" ]; then
            echo "::error title=Secret Missing::A secret SUPABASE_DB_URL_PROD não foi encontrada nas configurações do seu repositório GitHub."
            exit 1
          fi
          supabase db push --db-url "$DB_URL"
